list(
  truth=list(
    n=100000
  ),
  measurement=list(
    "measM"=list(
      measFn = "measurement1",
      options=list(
        cohorts=list(
          "younger"=list(
            obs=c("V","M"),
            n=2500
          ),
          "older"=list(
            obs=c("M","Y"),
            n=2500
          )
        )
      )
    )
  ),
  distances=list(
    #Only using unweighted in dag 1 because there's only one M so weighting is meaningless
    "euclidian_spec"=list(
      distanceFn="euclidian",
      options=list(
        vars=c("M"),
        distanceMetric="unweighted"
      )
    )
  ),
  combining=list(
    "detMatch_10Matches"=list(
      combFn="deterministicMatch",
      options=list(
        nMatches=10,
        nBootstraps=1,
        distance="euclidian_spec"
      )
    ),
    "detMatch_30Matches"=list(
      combFn="deterministicMatch",
      options=list(
        nMatches=30,
        nBootstraps=1,
        distance="euclidian_spec"
      )
    )
  ),
  analysis=list(
    "lm_V"=list(
      analysisFn="lm",
      options=list(
        formula="Y~V"
      )
    ),
    "lm_V_weighted"=list(
      analysisFn="lm",
      options=list(
        trimWeights=TRUE,
        weighted=TRUE,
        formula="Y~V"
      )
    ),
    "lmcluster_V"=list(
      analysisFn="lmcluster",
      options=list(
        formula="Y~V",
        weighted=FALSE,
        clusterVar="older"
      )
    ),
    "lmcluster_V_weighted"=list(
      analysisFn="lmcluster",
      options=list(
        formula="Y~V",
        trimWeights=TRUE,
        weighted=TRUE,
        clusterVar="older"
      )
    ),
    "lmMI_V"=list(
      analysisFn="lm_MIpool",
      options=list(
        formula="Y~V",
        clusterVar="older"
      )
    )
  ),
  dags = list(
    "dag_turtle"=list(
      measurement=list(
        "measM" = c("lm_V",
                    "lmcluster_V",
                    "lmMI_V"
        )
      ),
      combining = c("detMatch_10Matches",
                    "detMatch_30Matches"
      )
    )
  ),
  effect = list(outcomes="Y",
                do="V")
)
