list(
  truth=list(
    n=100000
  ),
  measurement=list(
    "measMM2"=list(
      measFn = "measurement1",
      options=list(
        cohorts=list(
          "younger"=list(
            obs=c("V","M","M2"),
            n=2500
          ),
          "older"=list(
            obs=c("M","M2","Y"),
            n=2500
          )
        )
      )
    )
  ),
  distances=list(
    "euclidian_spec"=list(
      distanceFn="euclidian",
      options=list(
        vars=c("M","M2"),
        distanceMetric="unweighted"
      )
    ),
    "euclidian_weighted_spec"=list(
      distanceFn="euclidian",
      options=list(
        vars=c("M","M2"),
        distanceMetric="rsq_weighted"
      )
    )
  ),
  combining=list(
    "detMatch_10Matches"=list(
      combFn="deterministicMatch",
      options=list(
        nMatches=10,
        nBootstraps=1,
        distance="euclidian_spec"
      )
    ),
    "detMatch_30Matches"=list(
      combFn="deterministicMatch",
      options=list(
        nMatches=30,
        nBootstraps=1,
        distance="euclidian_spec"
      )
    ),

    "detMatch_10Matches_weighted"=list(
      combFn="deterministicMatch",
      options=list(
        nMatches=10,
        nBootstraps=1,
        distance="euclidian_weighted_spec"
      )
    ),
    "detMatch_30Matches_weighted"=list(
      combFn="deterministicMatch",
      options=list(
        nMatches=30,
        nBootstraps=1,
        distance="euclidian_weighted_spec"
      )
    )
  ),
  analysis=list(
    "lm_V"=list(
      analysisFn="lm",
      options=list(
        formula="Y~V"
      )
    ),
    "lmcluster_V"=list(
      analysisFn="lmcluster",
      options=list(
        formula="Y~V",
        weighted=FALSE,
        clusterVar="older"
      )
    ),
    "lmMI_V"=list(
      analysisFn="lm_MIpool",
      options=list(
        formula="Y~V",
        clusterVar="older"
      )
    )
  ),
  dags = list(
    "dag_bat"=list(
      measurement=list(
        "measMM2" = c("lmMI_V")
      ),
      combining = c("detMatch_10Matches",
                    "detMatch_30Matches",
                    "detMatch_10Matches_weighted",
                    "detMatch_30Matches_weighted")
    )
  ),
  effect = list(outcomes="Y",
                do="V")
)
