list(
  truth=list(
    n=100000
  ),
  measurement=list(
    "measCM_both"=list(
      measFn = "measurement1",
      options=list(
        cohorts=list(
          "younger"=list(
            obs=c("V","M","C"),
            n=2500
          ),
          "older"=list(
            obs=c("C","M","Y"),
            n=2500
          )
        )
      )
    )
  ),
  distances=list(
    "euclidian_spec"=list(
      distanceFn="euclidian",
      options=list(
        vars=c("C","M"),
        distanceMetric="unweighted"
      )
    ),
    "euclidian_weighted_spec"=list(
      distanceFn="euclidian",
      options=list(
        vars=c("C","M"),
        distanceMetric="rsq_weighted"
      )
    )
  ),
  combining=list(
    "detMatch_10Matches"=list(
      combFn="deterministicMatch",
      options=list(
        nMatches=10,
        nBootstraps=1,
        distance="euclidian_spec"
      )
    ),
    "detMatch_30Matches"=list(
      combFn="deterministicMatch",
      options=list(
        nMatches=30,
        nBootstraps=1,
        distance="euclidian_spec"
      )
    ),
    "detMatch_10Matches_weighted"=list(
      combFn="deterministicMatch",
      options=list(
        nMatches=10,
        nBootstraps=1,
        distance="euclidian_weighted_spec"
      )
    ),
    "detMatch_30Matches_weighted"=list(
      combFn="deterministicMatch",
      options=list(
        nMatches=30,
        nBootstraps=1,
        distance="euclidian_weighted_spec"
      )
    )
  ),
  analysis=list(
    "lm_VC"=list(
      analysisFn="lm",
      options=list(
        formula="Y~V+C"
      )
    ),
    "lmcluster_VC"=list(
      analysisFn="lmcluster",
      options=list(
        formula="Y~V+C",
        weighted=FALSE,
        clusterVar="older"
      )
    ),
    "lmMI_VC"=list(
      analysisFn="lm_MIpool",
      options=list(
        formula="Y~V+C",
        clusterVar="older"
      )
    )
  ),
  dags = list(
    "dag_dromedary_strongconf_MgtC_newParams"=list(
      measurement=list(
        "measCM_both" = c("lmMI_VC")
      ),
      combining = c("detMatch_10Matches",
                    "detMatch_30Matches",
                    "detMatch_10Matches_weighted",
                    "detMatch_30Matches_weighted")
    )
  ),
  effect = list(outcomes="Y",
                do="V")
)
